# GitHub Pages configuration
title: Ajai Prakash V | Portfolio
description: Professional portfolio of Ajai Prakash V, Software Development Engineer
baseurl: ""
url: "https://17csr007.github.io/portfolio"
